name: Build teamcity-agent docker

on:
  push:
    branches: ["main", "dev*"]
    tags: ["minver-*.*.*", "minver-*.*"]
  pull_request:
    branches: [main]

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest]
    name: build-${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ secrets.DOCKER_HUB_MINVER_CLI_REPOS }}
            teslaconsulting/minver-cli
          tags: |
            type=ref,event=branch,priority=600
            type=sha,enable=true,priority=500,prefix=sha-,suffix=,format=short
            type=match,enable=true,priority=900,prefix=,suffix=,pattern=^minver-(\d+\.\d+(\.\d+)?(-.+)?)$,group=1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./minver
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
